library(devtools)

devtools::install_version("BiocManager", 
                          version = "1.30.16",
                          repos = "http://cran.us.r-project.org", 
                          upgrade = "never", 
                          force = FALSE)

BiocManager::install(version = '3.14', 
                     update = FALSE, 
                     ask = FALSE)

bioconductor.packages <- c("anndata",
                           "ape",
                           "AUCell",
                           "batchelor",
                           "Biobase",
                           "BiocParallel",
                           "biomaRt",
                           "calibrate",
                           "caret",
                           "celldex",
                           "checkmate",
                           "circlize",
                           "cluster",
                           "clusterProfiler",
                           "clustifyr",
                           "ComplexHeatmap",
                           "corrplot",
                           "cowplot",
                           "data.table",
                           "DelayedArray",
                           "DelayedMatrixStats",
                           "distill",
                           "doMC",
                           "doParallel",
                           "doRNG",
                           "DOSE",
                           "dplyr",
                           "DT",
                           "edgeR",
                           "EnhancedVolcano",
                           'enrichplot',
                           "factoextra",
                           "FactoMineR",
                           "fgsea",
                           "formattable",
                           "fs",
                           "future",
                           "future.apply",
                           "ggalluvial",
                           "ggbeeswarm",
                           "ggfittext",
                           "gghalves",
                           "ggnewscale",
                           "ggplot2",
                           "ggpubr",
                           "ggrepel",
                           "ggsci",
                           "ggThemeAssist",
                           "ggthemes",
                           "ggtree",
                           "gplots",
                           "graphite",
                           "gridExtra",
                           "GSEABase",
                           "GSVA",
                           "harmony",
                           "hdf5r",
                           "Hmisc",
                           "igraph",
                           "inlmisc",
                           "janitor",
                           "kernlab",
                           "knitr",
                           "limma",
                           "locfit",
                           "lubridate",
                           "magick",
                           "metap",
                           "MLmetrics",
                           "msigdbr",
                           "multtest",
                           "mutoss",
                           "Nebulosa",
                           "org.Hs.eg.db",
                           "org.Mm.eg.db",
                           "paletteer",
                           "pals",
                           "patchwork",
                           "pbapply",
                           "pcaMethods",
                           "PerformanceAnalytics",
                           "pheatmap",
                           "plyr",
                           "pROC",
                           "progeny",
                           "R.utils",
                           "RcisTarget",
                           "RColorBrewer",
                           "reactome.db",
                           "ReactomePA",
                           "readr",
                           "readxl",
                           "remedy",
                           "renv",
                           "reticulate",
                           "Rgraphviz",
                           "rmarkdown",
                           "RobustRankAggreg",
                           "rstudioapi",
                           "RVenn",
                           "scales",
                           "scico",
                           "scRepertoire",
                           "SeuratObject",
                           "Seurat",
                           "SingleCellExperiment",
                           "singleCellHaystack",
                           "SingleR",
                           "singscore",
                           "stringr",
                           "styler",
                           "SummarizedExperiment",
                           "survival",
                           "tictoc",
                           "tibble",
                           "UpSetR",
                           "useful",
                           "usethis",
                           "viridis",
                           "visNetwork")

bioconductor.packages <- unique(bioconductor.packages)

BiocManager::install(bioconductor.packages, 
                     ask = FALSE, 
                     update = FALSE,
                     version="3.14")
